# Generated by Django 3.1.1 on 2020-09-28 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jobId', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dateRequested', models.DateTimeField(auto_now_add=True)),
                ('jobcompleted', models.BooleanField(default=False)),
                ('paymentCompleted', models.BooleanField(default=False)),
                ('fileName', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('jobDetails', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users', verbose_name='Users')),
            ],
            options={
                'ordering': ['-dateRequested'],
            },
        ),
    ]
