# Generated by Django 3.1.1 on 2020-09-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastAccessDate', models.DateTimeField()),
                ('isAdminUser', models.BooleanField(verbose_name=False)),
            ],
            options={
                'ordering': ['-username'],
            },
        ),
    ]
